### ISSUE TITLE
how about using arrow function inside classes?

### ISSUE THREAD

**Issue by prscX** [swipesapp/react-delegate#1]
As per my understanding babeljs provides experimental feature through which we can use arrow functions inside JS classes, by using this we can probably achieve what we are trying do using this library

Please refer below example for the same:
[Example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=MYGwhgzhAEDKCmYBOwAWAxA9kgttA3gLABQ00wmAdhAC5ICuwN2AFAJQElkC-JX0AE0yxMOeDVQBLSgHNoAXmjsFAPk6ky0fr2LcgA&experimental=true&loose=false&spec=false)

Please let me know in case I am missing anything

**Comment by kasperpihl** [comment]
The idea is that it's a parent that is called. Not an internal method of the class :)
